---
language: python

python:
  - '3.6'

install:
  - pip install -q -r requirements-dev.txt .

script:
  - make test

notifications:
  email: false

deploy:
  provider: pypi
  user: jojje
  password:
    secure: "fmbs10V2E0jX2UV7kdfgW34vgvObm6W1n7DLi1xB1tOmNXLCK9AzkiihRvpaG6Bw1Stp8xibJv8TaPI72RIgIOritOTb9y9KenJuUEmS5TT1sJwo6pJx8AM03dp9MVnLpGKyKH/IVnWNavjwf3+xcLwWqHjm3nCHj0AdZtekHEdJh6H1KHW3+7WXZcyBzyIP4kvuuxtDRcyvfTTKT6Eq+/GB4jKCWZ3ecE47z0V88lnS3Hu0ZIbEFo4rU1mDy+Qo2OyEMReJZzTQhAh/O1rDVkH7MGQGj8c9aBxkgWSbZXhMFIGSDSj3vy5TysVDZ2kSqLNOywEDFRtrw4w9RDRScKASla4iQZXoZTThm4pTLp/L2v3aOIZpnXLRin2PmUgU/zfAX4CNnjzeqKEu5y8cxpXcztw6Dvi8HI0wY4PoQQQSy9wOu4BobFPnNVBALpmldSsHa18743GbKTe+hyjCC9xswIwxf0QEwLoiswd9GktDrNXEQb/fDncl2iMpxATBcZc2GpZW4tL6tcWoAL8FAYT2Edam8yHRWS0ENdUmeZwkZIMBHLOH8ThBgOqQ3KCsAFrAD9lTBUK5mRrwzrlo8+EtgZGWq8DwosGRgSxzbPkoFYwE9nZKx0ct7DDZMxntvIj73r/AtoWlOGzC+WIRg+DkxfSjKvcsQO/FRNjCX/A="
  distributions: sdist bdist_wheel
  on:
    tags: true